version: "2"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build:
      context: ./docker/php
    working_dir: /work
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - database
      - redis
  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=laravel"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
